### ISSUE TITLE
Pycharm 2017.1 community Failed to generate a valid skeleton for 'base'.

### ISSUE THREAD

**Issue by brendankeane** [holgerbrandl/r4intellij#105] opened 2017-05-31 15:35 UTC
Doing what the machine asked.

Failed to generate a valid skeleton for 'base'. Please file a ticket under https://github.com/holgerbrandl/r4intellij/issues
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:132)
	at com.r4intellij.packages.RSkeletonGenerator.lambda$updateSkeletons$1(RSkeletonGenerator.java:247)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by holgerbrandl** [comment] 2017-08-12 08:56
Duplicate of #120

**Closed by holgerbrandl** 2017-08-12 08:56 UTC
