### ISSUE TITLE
Error in Intellij on plugin update: IndexOutOfBoundsException

### ISSUE THREAD

**Issue by Terry-Weymouth** [holgerbrandl/r4intellij#111] opened 2017-07-07 13:46 UTC
The following error was reported by the Intellij error interface just after the update of the R Language plugin, before any action on my part. 
(Plugin version 1.0.6) 

Index: 1, Size: 1
java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at com.r4intellij.packages.PackageServiceUtilKt.getInstalledPackageVersions(PackageServiceUtil.kt:151)
	at com.r4intellij.packages.RSkeletonGenerator.updateSkeletons(RSkeletonGenerator.java:158)
	at com.r4intellij.packages.RSkeletonGenerator.access$000(RSkeletonGenerator.java:54)
	at com.r4intellij.packages.RSkeletonGenerator$1.run(RSkeletonGenerator.java:105)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:726)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:163)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:137)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:334)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by haesleinhuepf** [comment] 2017-07-07 13:51
I can reproduce the issue. It happens for example when you open a freshly checkout maven project which contains no R files at all.

**Comment by holgerbrandl** [comment] 2017-07-07 17:09
Please update to 1.0.7. I did not fix anything because I could not reproduce it. However the error should now include more details that will help to trace it down. So please reattach the extended error output to this ticket if the error happens again.

@haesleinhuepf btw 1.0.7 is the first airport-terminal-release on the way back from user2017. :-)

**Comment by holgerbrandl** [comment] 2017-07-07 17:11
duplicate of #99

**Closed by holgerbrandl** 2017-07-07 17:11 UTC
