### ISSUE TITLE
Failed to generate a valid skeleton for 'base'

### ISSUE THREAD

**Issue by cloaked-ninja** [holgerbrandl/r4intellij#101] opened 2017-05-17 20:08 UTC
Hi, using Microsoft Open R. 

Set the language interpreter to C:/Program%20Files/Microsoft/MRO-3.3.2/bin/x64/r.exe.  
After clicking apply, the progress bar showed updating for a couple of minutes, then received this error message:

> Failed to generate a valid skeleton for 'base'. Please file a ticket under https://github.com/holgerbrandl/r4intellij/issues

Details:
`Failed to generate a valid skeleton for 'base'. Please file a ticket under https://github.com/holgerbrandl/r4intellij/issues
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:132)
	at com.r4intellij.packages.RSkeletonGenerator.lambda$updateSkeletons$1(RSkeletonGenerator.java:247)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)`

**Comment by holgerbrandl** [comment] 2017-05-19 14:23
Could you follow the instructions on http://holgerbrandl.github.io/r4intellij/faq.html#r4intellij-fails-to-index-package-xy-what-canshould-i-do and attach more info as described there? Thanks.

**Comment by holgerbrandl** [comment] 2017-05-19 14:23
At the moment the plugin is also developed and tested just against the R from r-project.org.

**Comment by holgerbrandl** [comment] 2017-08-12 08:57
Duplicate of #120. Please comment on the other ticket instead if needed.

**Closed by holgerbrandl** 2017-08-12 08:57 UTC
