### ISSUE TITLE
Error when trying to use the Debug

### ISSUE THREAD

**Issue by jeryTymate** [holgerbrandl/r4intellij#128] opened 2017-10-10 09:38 UTC
I created a new project with one r file.
I checked the project configuration and R interpreter are set.

But when I clic on the debug button (to test breakpoints), I have an error box which says:

> Actual type is not the same as expected: [actual: RESPONSE, expected: DEBUG_AT]

```Actual type is not the same as expected: [actual: RESPONSE, expected: DEBUG_AT]
com.r4intellij.debugger.exception.RUnexpectedExecutionResultTypeException: Actual type is not the same as expected: [actual: RESPONSE, expected: DEBUG_AT]
	at com.r4intellij.debugger.executor.RExecutorUtils.execute(RExecutorUtils.java:20)
	at com.r4intellij.debugger.function.RFunctionDebuggerBase.initCurrentLine(RFunctionDebuggerBase.java:148)
	at com.r4intellij.debugger.function.RFunctionDebuggerBase.<init>(RFunctionDebuggerBase.java:61)
	at com.r4intellij.debugger.function.RBraceFunctionDebugger.<init>(RBraceFunctionDebugger.java:19)
	at com.r4intellij.debugger.function.RFunctionDebuggerFactoryImpl.getFunctionDebugger(RFunctionDebuggerFactoryImpl.java:37)
	at com.r4intellij.debugger.RDebugger.prepareDebug(RDebugger.java:185)
	at com.r4intellij.debugger.RDebugger.advance(RDebugger.java:113)
	at com.r4intellij.run.debug.RDebugProcess.advance(RDebugProcess.java:299)
	at com.r4intellij.run.debug.RDebugProcess.access$100(RDebugProcess.java:41)
	at com.r4intellij.run.debug.RDebugProcess$4.run(RDebugProcess.java:221)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
Does anyone know how to fix that?
Thank you ;)

**Comment by holgerbrandl** [comment] 2017-10-25 08:49
Works for me. What version of R, Intellij and the plugin are you using?

**Comment by DuM4ll3** [comment] 2017-11-28 21:12
Same here.
I'm using PyCharm CE - October 19/2017 build.
Plugin v1.0.8
Installed R using the CRAM Mac OS installer v.3.4.2

**Comment by daimingzhong** [comment] 2018-02-08 04:00
I have the same problem in Mac OS with PyCharm professional.

**Comment by holgerbrandl** [comment] 2018-02-08 15:45
Duplicate of #139

**Closed by holgerbrandl** 2018-02-08 15:45 UTC
