### ISSUE TITLE
Unable to generate "base" skeleton for R-3.4.0, windows, 64-bit.

### ISSUE THREAD

**Issue by qhalid** [holgerbrandl/r4intellij#106] opened 2017-06-02 14:18 UTC
Failed to generate a valid skeleton for 'base'. Please file a ticket under https://github.com/holgerbrandl/r4intellij/issues
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:132)
	at com.r4intellij.packages.RSkeletonGenerator.lambda$updateSkeletons$1(RSkeletonGenerator.java:247)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by qhalid** [comment] 2017-06-02 14:39
I ran "R -f skeletonize_package.R --args base base.skeleton.R.txt > skeletonize_package.R.stdout.txt

If I take the resulting skeleton file, rename it, and place it in the r_skeletons directory, I am able to again resolve references in the base package in the IDE.

[skeletonize_package.R.stdout.txt](https://github.com/holgerbrandl/r4intellij/files/1047995/skeletonize_package.R.stdout.txt)
[base.skeleton.R.txt](https://github.com/holgerbrandl/r4intellij/files/1047996/base.skeleton.R.txt)

**Comment by jkl1337** [comment] 2017-07-27 03:20
I see the same behavior with R 3.4.1 on x64 Windows

**Comment by tjakobi** [comment] 2017-07-28 10:57
I can confirm changing from R 3.4.1 to 3.3.3 also fixed this issue for me.

**Comment by holgerbrandl** [comment] 2017-08-12 08:55
duplicate of #120

**Closed by holgerbrandl** 2017-08-12 08:55 UTC
