### ISSUE TITLE
Failed to generate a valid skeleton for 'base'.

### ISSUE THREAD

**Issue by ArturHD** [holgerbrandl/r4intellij#119] opened 2017-08-01 15:27 UTC
Failed to generate a valid skeleton for 'base'. Please file a ticket under https://github.com/holgerbrandl/r4intellij/issues
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:132)
	at com.r4intellij.packages.RSkeletonGenerator.lambda$updateSkeletons$1(RSkeletonGenerator.java:248)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

-----
Environment data:
** R version 3.4.1 (2017-06-30) -- "Single Candle"
Platform: x86_64-w64-mingw32/x64 (64-bit)

** Windows 10 professional, German

** R packages:

                   Package   Version
                   acepack     1.4.1
 AppliedPredictiveModeling     1.1-6
                assertthat     0.2.0
                 backports     1.1.0
                 base64enc     0.1-3
                  beanplot       1.2
                        BH  1.62.0-1
                     bindr       0.1
                  bindrcpp       0.2
                    bitops     1.0-6
                      brew     1.0-6
                       bst    0.3-14
                       car     2.1-5
                     caret    6.0-76
                   caTools    1.17.1
                 checkmate     1.8.3
                     chron    2.3-50
                      coin     1.2-1
                colorspace     1.3-2
                 CORElearn    1.50.3
                  corrplot      0.77
                    crayon     1.3.2
                    Cubist    0.0.19
                      curl       2.7
                data.table    1.10.4
                       DBI       0.7
                   deepnet       0.2
                  devtools    1.13.2
                DiagrammeR     0.9.0
                 dichromat     2.0-0
                    digest    0.6.12
                doParallel    1.0.10
                     dplyr     0.7.1
                    dtplyr     0.0.2
                     e1071     1.6-8
                     earth     4.5.0
                  evaluate    0.10.1
                   foreach     1.4.3
                   Formula     1.2-2
                       gbm     2.1.3
                     gdata    2.18.0
                     GenSA     1.1.6
                   ggplot2     2.2.1
                     git2r    0.18.0
                      glue     1.1.1
                     GPfit     1.0-0
                    gplots     3.0.1
                  gridBase     0.4-7
                 gridExtra     2.2.1
                    gtable     0.2.0
                    gtools     3.5.0
                     highr       0.6
                     Hmisc     4.0-3
                       hms       0.3
                 htmlTable       1.9
                 htmltools     0.3.6
               htmlwidgets       0.8
                    httpuv     1.3.5
                      httr     1.2.1
                    igraph     1.0.1
                influenceR     0.1.0
                     irlba     2.2.1
                 iterators     1.0.8
                  jsonlite       1.5
                     knitr      1.16
                  labeling       0.3
              latticeExtra    0.6-28
                  lazyeval     0.2.0
                       lhs      0.14
                      lme4    1.1-13
                  magrittr       1.5
                  markdown       0.8
              MatrixModels     0.4-1
                   memoise     1.1.0
                      mime       0.5
                     minqa     1.2.4
              ModelMetrics     1.1.0
                modeltools    0.2-21
                  multcomp     1.4-6
                   munsell     0.4.3
                   mvtnorm     1.0-6
                     mxnet    0.10.1
                 neuralnet      1.33
                    nloptr     1.0.4
                       NMF    0.20.6
                   openssl     0.9.6
                      pack     0.1-1
                  pbkrtest     0.4-7
      PerformanceAnalytics  1.4.3541
                 pkgconfig     2.0.1
                  pkgmaker      0.22
                     plogr     0.1-1
                    plotmo     3.3.3
                   plotrix     3.6-5
                       pls     2.6-0
                      plyr     1.8.4
                    praise     1.0.0
                 PythonInR     0.1-3
                  quantmod    0.4-10
                  quantreg      5.33
                        R6     2.2.2
              randomForest    4.6-12
     rBayesianOptimization     1.1.0
              RColorBrewer     1.1-2
                      Rcpp   0.12.12
                 RcppEigen 0.3.3.3.0
                     RCurl  1.95-4.8
                     readr     1.1.1
                  registry       0.3
                   reshape     0.8.6
                  reshape2     1.4.2
                     rgexf    0.15.3
                     rJava     0.9-8
                     rlang     0.1.1
                  rngtools     1.2.4
                      Rook     1.1-1
                    Rsolnp      1.16
                rstudioapi       0.6
                  sandwich     2.3-4
                    scales     0.4.1
                     shiny     1.0.3
               sourcetools     0.1.6
                   SparseM      1.77
                   stringi     1.1.5
                   stringr     1.2.0
                     swirl     2.4.3
             TeachingDemos      2.10
                  testthat     1.0.2
                   TH.data     1.0-8
                    tibble     1.3.3
                     tidyr     0.6.3
              translations     3.4.1
                 truncnorm     1.0-7
                       TTR    0.23-1
                   viridis     0.4.0
               viridisLite     0.2.0
                visNetwork     2.0.0
                   whisker     0.3-2
                     withr     1.0.2
                 XLConnect    0.2-13
             XLConnectJars    0.2-13
                       XML  3.98-1.9
                    xtable     1.8-2
                       xts    0.10-0
                      yaml    2.1.14
                       zoo     1.8-0

**Comment by holgerbrandl** [comment] 2017-08-12 08:55
duplicate of #120

**Closed by holgerbrandl** 2017-08-12 08:55 UTC
